FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY tests/generate_test_topics.py /app/generate_test_topics.py
ENV PYTHONUNBUFFERED=1

ENTRYPOINT ["python", "/app/generate_test_topics.py"]