apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server-0.properties: |
    broker.id=0
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka-0.kafka-headless:9092
    controller.quorum.voters=0@kafka-0.kafka-headless:9093,1@kafka-1.kafka-headless:9093,2@kafka-2.kafka-headless:9093
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    process.roles=broker,controller
    node.id=0
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.dirs=/tmp/kraft-combined-logs
    group.initial.rebalance.delay.ms=0
    cluster.id=MkU3OEVBNTcwNTJENDM2Qk
    format.version=1
  server-1.properties: |
    broker.id=1
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka-1.kafka-headless:9092
    controller.quorum.voters=0@kafka-0.kafka-headless:9093,1@kafka-1.kafka-headless:9093,2@kafka-2.kafka-headless:9093
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    process.roles=broker,controller
    node.id=1
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.dirs=/tmp/kraft-combined-logs
    group.initial.rebalance.delay.ms=0
    cluster.id=MkU3OEVBNTcwNTJENDM2Qk
    format.version=1
  server-2.properties: |
    broker.id=2
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093
    advertised.listeners=PLAINTEXT://kafka-2.kafka-headless:9092
    controller.quorum.voters=0@kafka-0.kafka-headless:9093,1@kafka-1.kafka-headless:9093,2@kafka-2.kafka-headless:9093
    controller.listener.names=CONTROLLER
    inter.broker.listener.name=PLAINTEXT
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    process.roles=broker,controller
    node.id=2
    offsets.topic.replication.factor=3
    transaction.state.log.replication.factor=3
    transaction.state.log.min.isr=2
    log.dirs=/tmp/kraft-combined-logs
    group.initial.rebalance.delay.ms=0
    cluster.id=MkU3OEVBNTcwNTJENDM2Qk
    format.version=1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:latest
        ports:
        - containerPort: 9092
          name: plaintext
        - containerPort: 9093
          name: controller
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_ORDINAL
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          # Extract the ordinal from the pod name
        command:
        - /bin/bash
        - -c
        - |
          ORDINAL=$(echo $POD_NAME | rev | cut -d'-' -f1 | rev)
          cp /config/server-$ORDINAL.properties /tmp/server.properties
          # Format the storage directory
          /opt/kafka/bin/kafka-storage.sh format -t MkU3OEVBNTcwNTJENDM2Qk -c /tmp/server.properties
          # Start the Kafka server
          exec /opt/kafka/bin/kafka-server-start.sh /tmp/server.properties
        volumeMounts:
        - name: kafka-data
          mountPath: /tmp/kraft-combined-logs
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: kafka-config
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
  - name: plaintext
    port: 9092
    targetPort: 9092