apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rp-exporter

resources:
  - namespace.yaml
  - storage.yaml
  - kafka.yaml
  - redpanda-console.yaml
  - rp-exporter.yaml
  - prometheus.yaml
  - grafana.yaml
  - topic-generator.yaml