apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-console-config
data:
  config.yaml: |
    kafka:
      brokers: ["kafka.rp-exporter.svc.cluster.local:9092"]
    redpanda:
      adminApi:
        enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: redpanda-console
        image: redpandadata/console:latest
        ports:
        - containerPort: 8080
        - containerPort: 9644
        env:
        - name: CONFIG_FILEPATH
          value: /etc/redpanda/console/config.yaml
        - name: KAFKA_BROKERS
          value: kafka.rp-exporter.svc.cluster.local:9092
        volumeMounts:
        - name: config
          mountPath: /etc/redpanda/console
      volumes:
      - name: config
        configMap:
          name: redpanda-console-config
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-console
spec:
  selector:
    app: redpanda-console
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30808
  - name: admin
    port: 9644
    targetPort: 9644
  type: NodePort