apiVersion: batch/v1
kind: Job
metadata:
  name: topic-generator
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: topic-generator
        image: topic-generator:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
      restartPolicy: Never
  backoffLimit: 2